allowBuilds:
  core-js-pure: true
  esbuild: true
  lefthook: true
  msw: true
  sharp: true
  unrs-resolver: true
minimumReleaseAgeExclude:
  - '@commitlint/cli@21.2.1'
  - '@commitlint/read@21.2.1'
  - '@types/node@26.1.1'
  - '@typescript/typescript-aix-ppc64@6.0.3'
  - '@typescript/typescript-darwin-arm64@6.0.3'
  - '@typescript/typescript-darwin-x64@6.0.3'
  - '@typescript/typescript-freebsd-arm64@6.0.3'
  - '@typescript/typescript-freebsd-x64@6.0.3'
  - '@typescript/typescript-linux-arm64@6.0.3'
  - '@typescript/typescript-linux-arm@6.0.3'
  - '@typescript/typescript-linux-loong64@6.0.3'
  - '@typescript/typescript-linux-mips64el@6.0.3'
  - '@typescript/typescript-linux-ppc64@6.0.3'
  - '@typescript/typescript-linux-riscv64@6.0.3'
  - '@typescript/typescript-linux-s390x@6.0.3'
  - '@typescript/typescript-linux-x64@6.0.3'
  - '@typescript/typescript-netbsd-arm64@6.0.3'
  - '@typescript/typescript-netbsd-x64@6.0.3'
  - '@typescript/typescript-openbsd-arm64@6.0.3'
  - '@typescript/typescript-openbsd-x64@6.0.3'
  - '@typescript/typescript-sunos-x64@6.0.3'
  - '@typescript/typescript-win32-arm64@6.0.3'
  - '@typescript/typescript-win32-x64@6.0.3'
  - lefthook-darwin-arm64@2.1.10
  - lefthook-darwin-x64@2.1.10
  - lefthook-freebsd-arm64@2.1.10
  - lefthook-freebsd-x64@2.1.10
  - lefthook-linux-arm64@2.1.10
  - lefthook-linux-x64@2.1.10
  - lefthook-openbsd-arm64@2.1.10
  - lefthook-openbsd-x64@2.1.10
  - lefthook-windows-arm64@2.1.10
  - lefthook-windows-x64@2.1.10
  - lefthook@2.1.10
  - msw@2.15.0
  - typescript@6.0.3
  - shadcn@4.13.1
  - '@next/env@16.3.0'
  - '@next/eslint-plugin-next@16.3.0'
  - '@next/swc-darwin-arm64@16.3.0'
  - '@next/swc-darwin-x64@16.3.0'
  - '@next/swc-linux-arm64-gnu@16.3.0'
  - '@next/swc-linux-arm64-musl@16.3.0'
  - '@next/swc-linux-x64-gnu@16.3.0'
  - '@next/swc-linux-x64-musl@16.3.0'
  - '@next/swc-win32-arm64-msvc@16.3.0'
  - '@next/swc-win32-x64-msvc@16.3.0'
  - '@storybook/addon-a11y@10.5.6'
  - '@storybook/addon-docs@10.5.6'
  - '@storybook/addon-onboarding@10.5.6'
  - '@storybook/addon-themes@10.5.6'
  - '@storybook/builder-webpack5@10.5.6'
  - '@storybook/core-webpack@10.5.6'
  - '@storybook/csf-plugin@10.5.6'
  - '@storybook/nextjs@10.5.6'
  - '@storybook/preset-react-webpack@10.5.6'
  - '@storybook/react-dom-shim@10.5.6'
  - '@storybook/react@10.5.6'
  - '@typescript-eslint/eslint-plugin@8.66.0'
  - '@typescript-eslint/parser@8.66.0'
  - '@typescript-eslint/project-service@8.66.0'
  - '@typescript-eslint/scope-manager@8.66.0'
  - '@typescript-eslint/tsconfig-utils@8.66.0'
  - '@typescript-eslint/type-utils@8.66.0'
  - '@typescript-eslint/types@8.66.0'
  - '@typescript-eslint/typescript-estree@8.66.0'
  - '@typescript-eslint/utils@8.66.0'
  - '@typescript-eslint/visitor-keys@8.66.0'
  - '@wrksz/themes@1.1.0'
  - eslint-config-next@16.3.0
  - eslint-plugin-storybook@10.5.6
  - next-i18next@16.0.10
  - next@16.3.0
  - storybook@10.5.6
  - typescript-eslint@8.66.0
