// This file is auto-generated by next-intl, do not edit directly.
// See: https://next-intl.dev/docs/workflows/typescript#messages-arguments

declare const messages: {
  "Home": {
    "welcome": "Bem-vindo!",
    "description": "Este é um exemplo para demonstração de internacionalização."
  }
};
export default messages;