import {
  LuAsterisk,
  LuBox,
  LuCalendar,
  LuCheck,
  LuChevronDown,
  LuChevronLeft,
  LuChevronRight,
  LuChevronsLeft,
  LuChevronsUpDown,
  LuChevronUp,
  LuCircleAlert,
  LuCircleCheck,
  LuCircleDollarSign,
  LuContainer,
  LuEllipsis,
  LuEllipsisVertical,
  LuEye,
  LuEyeOff,
  LuHouse,
  LuImage,
  LuInfo,
  LuLoaderCircle,
  LuLogOut,
  LuMinus,
  LuMonitor,
  LuMoon,
  LuPlus,
  LuSearch,
  LuSettings,
  LuStar,
  LuSun,
  LuTriangleAlert,
  LuUser,
  LuX,
} from 'react-icons/lu'

export const Icons = {
  Info: LuInfo,
  CircleAlert: LuCircleAlert,
  CircleCheck: LuCircleCheck,
  TriangleAlert: LuTriangleAlert,
  Star: LuStar,
  Asterisk: LuAsterisk,
  Box: LuBox,
  Check: LuCheck,
  Minus: LuMinus,
  Plus: LuPlus,
  EyeOff: LuEyeOff,
  Eye: LuEye,
  Loader: LuLoaderCircle,
  Image: LuImage,
  X: LuX,
  CircleDollarSign: LuCircleDollarSign,
  House: LuHouse,
  Settings: LuSettings,
  User: LuUser,
  Search: LuSearch,
  Moon: LuMoon,
  Sun: LuSun,
  Ellipsis: LuEllipsis,
  EllipsisVertical: LuEllipsisVertical,
  ChevronRight: LuChevronRight,
  ChevronsLeft: LuChevronsLeft,
  ChevronLeft: LuChevronLeft,
  ChevronUp: LuChevronUp,
  SignOut: LuLogOut,
  Monitor: LuMonitor,
  ChevronDown: LuChevronDown,
  ChevronsUpDown: LuChevronsUpDown,
  Container: LuContainer,
  Calendar: LuCalendar,
}
