import {
  LuBox,
  LuCalendar,
  LuCheck,
  LuChevronDown,
  LuChevronRight,
  LuChevronsLeft,
  LuChevronsUpDown,
  LuCircleDollarSign,
  LuContainer,
  LuEllipsis,
  LuEllipsisVertical,
  LuEye,
  LuEyeOff,
  LuHouse,
  LuImage,
  LuLoader,
  LuLogOut,
  LuMinus,
  LuMonitor,
  LuMoon,
  LuSearch,
  LuSettings,
  LuSun,
  LuUser,
  LuX,
} from 'react-icons/lu'

export const Icons = {
  Box: LuBox,
  Check: LuCheck,
  Minus: LuMinus,
  EyeOff: LuEyeOff,
  Eye: LuEye,
  Loader: LuLoader,
  Image: LuImage,
  X: LuX,
  CircleDollarSign: LuCircleDollarSign,
  House: LuHouse,
  Settings: LuSettings,
  User: LuUser,
  Search: LuSearch,
  Moon: LuMoon,
  Sun: LuSun,
  Ellipsis: LuEllipsis,
  EllipsisVertical: LuEllipsisVertical,
  ChevronRight: LuChevronRight,
  ChevronsLeft: LuChevronsLeft,
  SignOut: LuLogOut,
  Monitor: LuMonitor,
  ChevronDown: LuChevronDown,
  ChevronsUpDown: LuChevronsUpDown,
  Container: LuContainer,
  Calendar: LuCalendar,
}
